# Generated by Django 4.2.7 on 2026-06-15 12:23

from django.db import migrations, models


def _has_column(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        columns = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return column_name in {column.name for column in columns}


def _purpose_field():
    field = models.CharField(
        choices=[('password_reset', 'Password reset')],
        default='password_reset',
        max_length=50,
    )
    field.set_attributes_from_name('purpose')
    return field


def add_purpose_column_if_missing(apps, schema_editor):
    password_reset_otp = apps.get_model('users', 'PasswordResetOTP')
    if not _has_column(schema_editor, password_reset_otp._meta.db_table, 'purpose'):
        schema_editor.add_field(password_reset_otp, _purpose_field())


def remove_purpose_column_if_present(apps, schema_editor):
    password_reset_otp = apps.get_model('users', 'PasswordResetOTP')
    if _has_column(schema_editor, password_reset_otp._meta.db_table, 'purpose'):
        schema_editor.remove_field(password_reset_otp, _purpose_field())


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registrationotp'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_purpose_column_if_missing, remove_purpose_column_if_present),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='passwordresetotp',
                    name='purpose',
                    field=models.CharField(
                        choices=[('password_reset', 'Password reset')],
                        default='password_reset',
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
