# Generated by Django 4.2.7 on 2026-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auth_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_CHANGE', 'Email Change'), ('LOGIN', 'Login')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('GOOGLE', 'Google')], max_length=20),
        ),
    ]
