# Generated by Django 4.2.7 on 2026-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_distance_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, choices=[('cm', 'Centimeters'), ('in', 'Inches')], decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], decimal_places=2, max_digits=5, null=True),
        ),
    ]
