# Generated by Django 4.2.7 on 2026-07-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_pendingregistration_profile_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='distance_unit',
            field=models.CharField(choices=[('km', 'Kilometers'), ('mile', 'Miles')], default='km', max_length=4),
        ),
    ]
