# Generated by Django 4.2.7 on 2026-07-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userprofile_distance_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='distance_unit',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='weight_kg',
        ),
    ]
